### PR TITLE
feat: add dashboard URL to service instance

### LINKED ISSUE #864: [FEATURE] Add `dashboard_url` property to `btp_subaccount_service_instance` Resource and Data Source
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

Instances of certain BTP services have a dashboard URL. For these cases in BTP cockpit, the instance name is a link and user can access the dashboard by following it.

When a service instance is created with the Terraform provider for SAP BTP, or an existing instance is accessed as a data source, the dashboard URL is not available and users have to use other BTP clients like the CLI or the Cockpit to find out the URL.

### Describe the solution you would like

Add a read-only, nullable `dashboard_url` property to the `btp_subaccount_service_instance` resource and data source, so that users can get this URL from the state or use it as an output.

### Describe alternatives you have considered

_No response_

### Additional context

The BTP CLI already returns the `dashboard_url` for service instances:

```
$ btp --format JSON get services/instance --name free_datasphere-service
{
  "id": "...",
  "ready": true,
  "last_operation": {
    ...
  },
  ...
  "dashboard_url": "https://markus-test.us20.hcs.cloud.sap",
  "context": {
    ...
  },
 ...
}
```

### PR DESCRIPTION
**Pull request by lechnerc77**
## Purpose

* Add the field `dashboard_url` as computed parameter to the resource and data source for service instance
* closes #864

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[X] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code via automated test

```bash
go test ./...
```

* Additional test steps

```
Regression test with provider version 1.4.0  
```

## What to Check

Verify that the following are valid:

* Automated tests are executed successfully
* Validate that no change does not cause incompatible change

## Other Information

n/a

## Checklist for reviewer

The following organizational tasks must be completed before merging this PR:

* [X] The PR is assigned to the Terraform project and a status is set (typically "in review").
* [X] The PR has the matching labels assigned to it.
* [X] The PR has a milestone assigned to it.
* [X] If the PR closes an issue, the issue is referenced.
* [X] Possible follow-up items are created and linked.

### CODE REVIEW

**Comment by lechnerc77** [comment]
Regression test done with HANA Cloud - due to computed field, change has no impact on existing states.
Customers can fetch the additional computed field via `terraform refresh` which will update the state without any impact on the provided resources on SAP BTP

**Comment by lechnerc77** [comment]
- Fixture Drift Detection check fails => OKAY due to re-recording of test fixtures
- Inclusive Language check fails => ACCEPTED due to upstream dependency

**Comment by lechnerc77** [comment]
@vipinvkmenon @CHERIANS: when doing the review, please also validate the regression e.g. via the sample configuration provided above.

**Comment by vipinvkmenon** [comment]
Verified

**Review by vipinvkmenon — APPROVED** [review]

**Pull request merged**
