### PR TITLE
feat: add iframe parameter to security settings

### LINKED ISSUE #904: [BUG] Trusted Domains in Subaccount are not added
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.5.0

### What version of the Terraform CLI are you using?

1.9.5

### What type of issue are you facing

bug report

### Describe the bug

Unfortunately, it is not possible to add the Trusted Domains in a subaccount.

**values.tfvars**
```terraform
    security = {
      default_identity_provider                = "sap.custom"
      access_token_validity                    = 3600
      refresh_token_validity                   = 86400
      treat_users_with_same_email_as_same_user = false      
      custom_email_domains                     = ["https://*.test.com"]
    }  
```

**variables.tf**
```terraform
variable "security" {
  description = "Security settings for the subaccount"
  type = object({
    default_identity_provider                = string
    custom_email_domains                     = list(string)
    access_token_validity                    = number
    refresh_token_validity                   = number
    treat_users_with_same_email_as_same_user = bool    
  })
  default = null
}

```

**main.tf**
```terraform
resource "btp_subaccount_security_settings" "security_settings" {
  subaccount_id                            = btp_subaccount.subaccount.id
  default_identity_provider                = var.security.default_identity_provider
  custom_email_domains                     = var.security.custom_email_domains
  access_token_validity                    = var.security.access_token_validity
  refresh_token_validity                   = var.security.refresh_token_validity
  treat_users_with_same_email_as_same_user = var.security.treat_users_with_same_email_as_same_user
}
```

### Expected Behavior

The trusted domains are added and visible in the SAP BTP Cockpit

https://help.sap.com/docs/btp/sap-business-technology-platform/configure-trusted-domains-for-sap-authorization-and-trust-management-service

### Steps To Reproduce

_No response_

### User's Role Collections

_No response_

### Add screenshots to help explain your problem

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lechnerc77**
## Purpose

* The parameter `iframe_domains` was added to the resources and data sources for security settings to be in sync with the BTP CLI
* The resources for security settings can now be imported
* According updates of the documentation and test cases
* closes #904

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[X] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code via automated test

```bash
go test ./...
```

## What to Check

Verify that the following are valid:

* Automated tests are executed successfully

## Other Information

Due to the `make fmt` some files have been formated that are not subject to the change

## Checklist for reviewer

The following organizational tasks must be completed before merging this PR:

* [X] The PR is assigned to the Terraform project and a status is set (typically "in review").
* [X] The PR has the matching labels assigned to it.
* [X] The PR has a milestone assigned to it.
* [X] If the PR closes an issue, the issue is referenced.
* [X] Possible follow-up items are created and linked.

### CODE REVIEW

**Comment by lechnerc77** [comment]
Drift detection error is okay, as the test fixtures for the resources and data sources had to be re-recorded

**Comment by diya-dhan** [comment]
In the files ```examples/resources/btp_globalaccount_security_settings/resource.tf``` and ```examples/resources/btp_subaccount_security_settings/resource.tf```,  the attribute ```iframe_domains```  is a shown as a **list** although the attribute is a **string** as per the schema. 

image

image

**Comment by diya-dhan** [comment]
In the file ```internal/provider/datasource_globalaccount_security_settings.go``` and ```internal/provider/datasource_globalaccount_security_settings_test.go```, the attribute ```iframe_domains``` is configured as **Optional** as well as **Computed**. This is being reflected in the documentation as well.

**Comment by lechnerc77** [comment]
> In the files `examples/resources/btp_globalaccount_security_settings/resource.tf` and `examples/resources/btp_subaccount_security_settings/resource.tf`, the attribute `iframe_domains` is a shown as a **list** although the attribute is a **string** as per the schema.
> 
> image image

Resolved

**Comment by lechnerc77** [comment]
> In the file `internal/provider/datasource_globalaccount_security_settings.go` and `internal/provider/datasource_globalaccount_security_settings_test.go`, the attribute `iframe_domains` is configured as **Optional** as well as **Computed**. This is being reflected in the documentation as well.

Fixed

**Comment by diya-dhan** [comment]
Drift detection can be ignored as fixtures were re-recorded

**Comment by diya-dhan** [comment]
Tested out changes, everything works fine

**Review by diya-dhan — APPROVED** [review]
changes look fine,  testing done as well

**Pull request merged**
