### PR TITLE
fix: data source service instance sharing

### LINKED ISSUE #754: [BUG] Missing information for service plan: is instance shareable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.1.0

### What version of the Terraform CLI are you using?

1.7.3

### What type of issue are you facing

bug report

### Describe the bug

Currently the data sources for service plans on subaccount level do not expose any information if the service plan supports instance sharing.
However this information is necessary in order to use the new feature for service instances namely activating the instance sharing introduced with PR #751  

### Expected Behavior

The data source `btp_subaccount_service_plan` and `btp_subaccount_service_plans` expose the information if the plan supports a instance sharing.

### Steps To Reproduce

You can check the available data via the BTP CLI:

```bash
btp --format json get services/plan --name lite --offering-name destination
```

You find the information in the metadata section as `supportsInstanceSharing`:

``` json
{
  "id": "cdf9c103-ef56-43e5-ac1d-4f1c5b15e05c",
  "ready": true,
  "name": "lite",
  "description": "Read and manage destination configurations (including related certificates) on account and service instance levels with auto-retrieving and caching of auth tokens",
  "catalog_id": "b3440416-15f9-11e7-bdac-02667c123456",
  "catalog_name": "lite",
  "free": true,
  "metadata": {
    "supportsInstanceSharing": true,
    "displayName": "lite",
    "bullets": [
      "Shared service resources for all applications",
      "Limit of 1000 configurations (destinations + certificates)"
    ]
  },
  "service_offering_id": "8627a19b-c397-4b1a-b297-6281bd46d8c3",
  "created_at": "2020-08-10T14:58:38.756598Z",
  "updated_at": "2024-03-25T18:11:22.731855Z",
  "labels": "commercial_name = lite"
}
```

### User's Role Collections

n/a

### Add screenshots to help explain your problem

n/a

### Additional context

n/a

### PR DESCRIPTION
**Pull request by lechnerc77**
## Purpose

* This PR introduces a new computed attribute for the service plan data sources that indicates if a service plan can be shared
* The metadata is not returned reliably so a nil reference check is implemented to ensure a stable handling of the data retrieval
* No resources are touched by this change
* In addition is fixes a small documentation glitch for the subaccount data source
* Closes #754 

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

```
[X] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code via automated test

```bash
go test ./...
```

## What to Check

Verify that the following are valid:

* Automated tests are executed successfully

## Other Information

The corresponding response model for the service plans (service manager) is manually adjusted as the API definition that is publicly available on api.sap.com does not match the internal API used by the BTP CLI backend namely the CIS CLI. 

## Checklist for reviewer

The following organizational tasks must be completed before merging this PR:

* [X] The PR is assigned to the Terraform project and a status is set (typically "in review").
* [X] The PR has the matching labels assigned to it.
* [X] The PR has a milestone assigned to it.
* [X] If the PR closes an issue, the issue is referenced.
* [X] Possible follow-up items are created and linked.

### CODE REVIEW

**Comment by lechnerc77** [comment]
Fixture drift is okay as test fixtures needed to be re-recorded due to data source schema change

**Comment by lechnerc77** [comment]
Inclusive language check is acceptable as warnings arise from upstream APIs we cannot fix

**Review by diya-dhan — COMMENTED** [review]
looks good

**Review by diya-dhan — APPROVED** [review]
looks good

**Comment by vipinvkmenon** [comment]
Looks good

**Pull request merged**
