### PR TITLE
feat: Improve matching of replayed interactions during test execution

### LINKED ISSUE #253: Improve matching of replayed interactions recorded for test execution
The matching of http requests to recorded interactions in test fixtures should consider any relevant information sent to the btp CLI server. Currently, the test setup is using the default matcher which means that only the HTTP method and the request URL are matched. That is, any change to a resource or datasource that corrupts a request body sent to the CLI server or removes it completely would not be detected by any test. Furthermore, a subtle bug that still produces a valid request might even be undetected during a re-recording of the fixture. For example, one could call a wrong facade and do some unrecoverable changes to a resource.

While it is not clear which information is 'relevant', I'd like to propose the following to begin with:

- The request URL.

- The HTTP method.

- The request body.
Assuming that the body is created in a deterministic way, we should be able to simply match it as string. Alternatively, we can still parse and compare the json tree.

- The subdomain header.
This header determines the affected GA (or SA in remote regions).

- The Custom IdP header.
This header determines the IAS tenant from which the ID token for the user is retrieved.

### PR DESCRIPTION
**Pull request by kuntzed**
## Purpose

Sets a custom request matcher which considers the following request properties:

- Request URL
- HTTP method
- Request body
- Subdomain header
- Custom IdP header
## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code

```
go test ./...
```

## What to Check

Verify that the following are valid

* tests should still be green

## Other Information

Resolves #253

### CODE REVIEW

**Comment by kuntzed** [comment]
Hi @v0lkc,
can you confirm that the request bodies are created by the provider in a deterministic way? Matching the bodies simply as strings seems to work but if this cannot be guaranteed, then we would need to parse the json content and match on object level or do some pragmatic check that for example simply compares the set of all keys and values.

**Comment by kuntzed** [comment]
The new request matcher revealed minor issues with the fixtures of three tests:

- internal/provider/resource_subaccount_environment_instance_test.go
This was fixed by using the constant "john.doe@int.test" as Id and Email in the environment instance parameters property.

- internal/provider/resource_directory_test.go
Here the fixture contained an extra ,"labels":"null" in the directory creation request. Unfortunately, this could not be re-recorded since I ran into the same problem as @v0lkc related to an unexpected 404 status code in the response from the CLI server. However, I manually checked that there were no additional deviations. Then I simply removed the "labels" property from the recorded request in the fixture.

- internal/provider/resource_subaccount_test.go
Here the fixture had two issues. First, there was a missing "betaEnabled":"false" in the subaccount creation request. While this could be corrected by re-recording the fixture, the re-recording revealed another issue. After creation, the resource's "usage" property contains "NOT_USED_FOR_PRODUCTION" instead of "UNSET" as expected by the test. This is a computed property, but I did not find the corresponding computation in the code.

It would be nice if someone else could have a look as well and confirm that the first two fixtures are now ok. For the problem with the "usage" property I would be happy if someone could check if this points to a missing computation or maybe a problem with the default value.

**Comment by kuntzed** [comment]
Update: The PR now includes fixes for all found issues. The 404 error was fixed by a workaround which came with another PR (see #264). All fixtures are now re-recorded.

**Review by lechnerc77 — APPROVED** [review]
lgtm

**Pull request merged**
